### ISSUE TITLE
Support read-only mode in pod security context

### ISSUE THREAD

**Issue by jesper7** [iterative/helm-charts#97]
Currently, enabling read-only mode in the security context for the UI pod causes it to crash.
This is because the UI uses server-side rendering and must write compiled files to the local filesystem. We should mount the directory for the compiled files as a volume to fix this.

**Comment by rishabhdas** [comment]
Additional Context:

Pod Security Context:

```yaml
securityContext:
    readOnlyRootFilesystem: true
    allowPrivilegeEscalation: false
    privileged: false
```

Pod Logs

```bash
$ kubectl logs studio-ui-7689b48fb9-k4m29 -n iterative-studio  
No certificates to update
yarn run v1.22.19
warning Skipping preferred cache folder "/home/node/.cache/yarn" because it is not writable.
warning Selected the next writable cache folder in the list, will be "/tmp/.yarn-cache-1000".
$ node scripts/prepare-build.js && next start
warning Cannot find a suitable global folder. Tried these: "/usr/local, /home/node/.yarn"
node:internal/fs/utils:347
    throw err;
    ^

Error: EROFS: read-only file system, open '/app/.next/server/pages/404.html'
    at Object.openSync (node:fs:590:3)
    at Object.writeFileSync (node:fs:2202:35)
    at walk (/app/scripts/prepare-build.js:66:10)
    at Object.<anonymous> (/app/scripts/prepare-build.js:71:1)
    at Module._compile (node:internal/modules/cjs/loader:1191:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1245:10)
    at Module.load (node:internal/modules/cjs/loader:1069:32)
    at Function.Module._load (node:internal/modules/cjs/loader:904:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
    at node:internal/main/run_main_module:22:47 {
  errno: -30,
  syscall: 'open',
  code: 'EROFS',
  path: '/app/.next/server/pages/404.html'
}
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

```
